'''
Created on 26-Nov-2013

@author: 00003179
'''

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
'''
def printFib():
    x = 0
    y = 1
    z = 0
    s = 0
    for i in range(10):
        z = x + y    
        x = y
        y = z    
        if z % 2 == 0:
            s = s + z
    print s

def formsol():
    x = y = 1
    sum = 0    
    while (sum < 1000000):
        sum += (x + y)
        x, y = x + 2 * y, 2 * x + 3 * y
    return sum

print formsol()